### ISSUE TITLE
Randomly kicked players and errors.

### ISSUE THREAD

**Issue by craftrise** [WolverinDEV/BungeeUtil#57]
##  INFO
 BungeeCord version: Latest - BungeeCord (We have +3000 players - 4 Bungeecord server - No viaversion)
 Spigot version: 1.8.8
 BungeeUtil version: Latest - 2.6

**Comment by WolverinDEV** [comment]
Hey,
I'm very proud that a soon big server uses BungeeUtils (could I may add your server in the spigot forum as example server?)
Now to your problem. 
That sometimes happens when a client clicks on a negative slot (outside the inventory I remember).
If you changed the exception policy in the config to just print and not print and kick than this should not have an effect on the user :)

**Comment by WolverinDEV** [comment]
~ Closed
Caused by no response)
